[package]
name = "psola"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
dasp = { version = "0.11.0", features = ["signal"] }

[dev-dependencies]
pitch-detection = "0.3.0"
serde = { version = "1.0.192", features = ["derive"] }
serde_json = "1.0.108"
